#include "tcs.h"

void tcsPosture ( double a, double b, double np, double p[3][3] )

/*
**  - - - - - - - - - - -
**   t c s P o s t u r e
**  - - - - - - - - - - -
**
**  In a "virtual telescope", calculate the mount posture matrix for
**  given roll, pitch and nonperpendicularity.
**
**  Given:
**     a        double        mount "roll" (Note 2)
**     b        double        mount "pitch" (Note 2)
**     np       double        roll/pitch nonperpendicularity (radians)
**
**  Returned:
**     p        double[3][3]  the boresight-to-aim rotation matrix
**
**  Notes:
**
**  1  A "virtual telescope" is a group of transformations that link
**     three sets of coordinates:
**
**       (i)  the target (where in the sky the source is);
**
**      (ii)  the pointing-origin (where in the focal plane the image
**            appears);
**
**     (iii)  the mount encoder readings (that cause the image of the
**            target to fall in the specified place in the focal plane).
**
**     The transformations are specified by various time-dependent
**     rotation matrices, pointing corrections, functions of rotator
**     angle and so on.  They form a chain:
**
**
**                [ TARGET ]             -> target [a,b]
**                     |
**        astronomical transformations   <- time, site
**                     |
**                 refraction            <- weather
**                     |
**              mount orientation        <- ae2mt
**                     |
**                  [ AIM ]
**                     |                 }
**                   roll                } <- encoder a, and ia
**                     |                 }
**            roll/pitch nonperp         } <- np
**                     |                 }
**                   pitch               } <- encoder b, and ib
**                     |                 }
**               [ BORESIGHT ]
**                     |
**                  guiding              <- ga, gb
**                     |
**               pointing origin         <- [x,y] and rotator angle
**                     |
**               [ TELESCOPE ]
**                     |
**                   flop                <- vertical deflection terms
**                     |
**             tel/pitch nonperp         <- collimation terms
**                     |
**                 [ 1,0,0 ]
**
**
**     Given any two of the three sets of coordinates (sky, pointing-
**     origin, mount), the missing coordinates can be deduced.  There is
**     only one mount, and hence all the virtual telescopes must share
**     the same encoder demands, namely those generated by the main
**     "mount tracking" virtual telescope.  The remaining virtual
**     telescopes implement such features as autoguiding and tip/tilt
**     secondary optics, either by deducing the image position for a
**     given target, or deducing the sky coordinates that correspond to
**     a given place in the focal plane.
**
**     In the present case, the matrix that links the BORESIGHT and
**     AIM vectors is determined, given the yxz Euler angles b+ib, np
**     and -(a+ia).
**
**  2  The supplied roll and pitch are already corrected for index
**     errors, i.e. the index errors ia and ib have been added to the
**     the encoder readings before the present function is called.
**
**  3  This routine is optimized for speed, and accordingly no validation
**     of the arguments is performed.  It is the caller's responsibility
**     to supply sensible values.
**
**  Last revision:   3 April 2001
**
**  Copyright P.T.Wallace.  All rights reserved.
*/

{
   double sb, cb, snp, cnp, sma, cma;



/* Functions of the three Euler angles. */
   sb = sin ( b );
   cb = cos ( b );
   snp = sin ( np );
   cnp = cos ( np );
   sma = - sin ( a );
   cma = cos ( a );

/* Form the +b(y) then +np(x) then -a(z) rotation matrix. */
   p[0][0] = cma * cb + sma * snp * sb;
   p[0][1] = sma * cnp;
   p[0][2] = - cma * sb + sma * snp * cb;
   p[1][0] = - sma * cb + cma * snp * sb;
   p[1][1] = cma * cnp;
   p[1][2] = sma * sb + cma * snp * cb;
   p[2][0] = cnp * sb;
   p[2][1] = - snp;
   p[2][2] = cnp * cb;

}
