#include "tcs.h"

void tcsSky2a_c ( double xtar, double ytar, double ztar,
                  double spm1[3][3],
                  FRAMETYPE frame, double sst, double cst,
                  double spm2[3][3],
                  double *xa, double *ya, double *za )

/*
**  - - - - - - - - - - -
**   t c s S k y 2 a _ c
**  - - - - - - - - - - -
**
**  In a "virtual telescope", use the two sky-patch matrices and an
**  intermediate rotation to transform the target position in Cartesian
**  form into the AIM vector (the direction in which to aim, in mount
**  coordinates).
**
**  Given:
**     xtar        double         target x-coordinate (Note 1)
**     ytar        double         target y-coordinate (Note 1)
**     ztar        double         target z-coordinate (Note 1)
**     spm1        double[3][3]   SPM #1 (Note 3)
**     frame       FRAMETYPE      tracking frame ID (Note 3)
**     sst         double         sine of sidereal time (Notes 2,3)
**     cst         double         cosine of LAST (Notes 2,3)
**     spm2        double[3][3]   SPM #2 (Note 3)
**
**  Returned:
**     xa          double         aim x-coordinate (Note 1)
**     ya          double         aim y-coordinate (Note 1)
**     za          double         aim z-coordinate (Note 1)
**
**  Defined in tcs.h:
**     FRAMETYPE   enum           frame types
**     AZEL_TOPO   FRAMETYPE      topocentric Az/El
**
**  Notes:
**
**  1  A "virtual telescope" is a group of transformations that link
**     three sets of coordinates:
**
**       (i)  the target (where in the sky the source is);
**
**      (ii)  the pointing-origin (where in the focal plane the image
**            appears);
**
**     (iii)  the mount encoder readings (that cause the image of the
**            target to fall in the specified place in the focal plane).
**
**     The transformations are specified by various time-dependent
**     rotation matrices, pointing corrections, functions of rotator
**     angle and so on.  They form a chain:
**
**
**                [ TARGET ]             <- target [x,y,z]
**                     v
**        astronomical transformations   <- time, site
**                     v
**                 refraction            <- weather
**                     v
**              mount orientation        <- ae2mt
**                     v
**                  [ AIM ]
**                     |
**                   roll                <- encoder a, and ia
**                     |
**            roll/pitch nonperp         <- np
**                     |
**                   pitch               <- encoder b, and ib
**                     |
**               [ BORESIGHT ]
**                     |
**                  guiding              <- ga, gb
**                     |
**               pointing origin         <- [x,y] and rotator angle
**                     |
**               [ TELESCOPE ]
**                     |
**                   flop                <- vertical deflection terms
**                     |
**             tel/pitch nonperp         <- collimation terms
**                     |
**                 [ 1,0,0 ]
**
**
**     Given any two of the three sets of coordinates (sky, pointing-
**     origin, mount), the missing coordinates can be deduced.  There is
**     only one mount, and hence all the virtual telescopes must share
**     the same encoder demands, namely those generated by the main
**     "mount tracking" virtual telescope.  The remaining virtual
**     telescopes implement such features as autoguiding and tip/tilt
**     secondary optics, either by deducing the image position for a
**     given target, or deducing the sky coordinates that correspond to
**     a given place in the focal plane.
**
**     In the present case, the AIM vector is calculated, starting
**     from the sky target expressed in Cartesian coordinates, as shown
**     by the arrows.
**
**  2  The arguments sst and cst are the sine and cosine of the local
**     apparent sidereal time.  Neither is used if the target frame is
**     topocentric Az/El.
**
**  3  The way frame, spm1, sst, cst and spm2 are used depends on the
**     type of target coordinates:
**
**       frame        FK4
**       target       Bxxxx RA,Dec, current date
**       spm1         mean RA,Dec -> geocentric apparent RA,Dec
**       sst,cst      RA,Dec -> HA,Dec
**       spm2         geocentric HA,Dec -> AIM
**
**       frame        FK5
**       target       Jxxxx RA,Dec, current date
**       spm1         mean RA,Dec -> geocentric apparent RA,Dec
**       sst,cst      RA,Dec -> HA,Dec
**       spm2         geocentric HA,Dec -> AIM
**
**       frame        APPT
**       target       geocentric apparent RA,Dec
**       spm1         identity matrix
**       sst,cst      RA,Dec -> HA,Dec
**       spm2         geocentric HA,Dec -> AIM
**
**       frame        APPT_TOPO
**       target       topocentric apparent RA,Dec
**       spm1         identity matrix
**       sst,cst      RA,Dec -> HA,Dec
**       spm2         topocentric HA,Dec -> AIM
**
**       frame        AZEL_TOPO
**       target       topocentric Az,El (N thru E)
**       spm1         identity matrix
**       sst,cst      not used
**       spm2         topocentric Az,El -> AIM
**
**     ICRS = FK5 J2000 to better than 25 mas.
**
**  Last revision:   5 March 2005
**
**  Copyright P.T.Wallace.  All rights reserved.
*/

{
   double x1, y1, z1, x2, y2, z2, x3, y3, z3, w;



/* Tracking frame to apparent RA,Dec (except for Az,El case). */
    x1 = spm1[0][0] * xtar + spm1[0][1] * ytar + spm1[0][2] * ztar;
    y1 = spm1[1][0] * xtar + spm1[1][1] * ytar + spm1[1][2] * ztar;
    z1 = spm1[2][0] * xtar + spm1[2][1] * ytar + spm1[2][2] * ztar;

/* Earth rotation, giving apparent -HA,Dec (except for Az,El case). */
    if (frame != AZEL_TOPO) {
       x2 = cst * x1 + sst * y1;
       y2 = -sst * x1 + cst * y1;
    } else {
       x2 = x1;
       y2 = y1;
    }
    z2 = z1;

/* To mount frame. */
    x3 = spm2[0][0] * x2 + spm2[0][1] * y2 + spm2[0][2] * z2;
    y3 = spm2[1][0] * x2 + spm2[1][1] * y2 + spm2[1][2] * z2;
    z3 = spm2[2][0] * x2 + spm2[2][1] * y2 + spm2[2][2] * z2;

/* Re-normalize (fast). */
    w = ( 3.0 - ( x3 * x3 + y3 * y3 + z3 * z3 ) ) / 2.0;
    *xa = x3 * w;
    *ya = y3 * w;
    *za = z3 * w;

}
