#include "tcs.h"

void tcsSky2aim ( double tara, double tarb,
                  double spm1[3][3],
                  FRAMETYPE frame, double sst, double cst,
                  double spm2[3][3],
                  double *xa, double *ya, double *za )

/*
**  - - - - - - - - - - -
**   t c s S k y 2 a i m
**  - - - - - - - - - - -
**
**  In a "virtual telescope", for the specified target, predict the
**  AIM vector (the direction in which to aim, in mount coordinates).
**
**  Given:
**     tara     double        target "roll" coordinate (Note 1)
**     tarb     double        target "pitch" coordinate (Note 1)
**     spm1     double[3][3]  SPM #1 (Note 3)
**     frame    FRAMETYPE     reference frame for the target (Note 3)
**     sst      double        sine of sidereal time (Notes 2,4)
**     cst      double        cosine of sidereal time (Notes 2,3)
**     spm2     double[3][3]  SPM #2 (Note 3)
**
**  Returned:
**     xa       double        aim x-coordinate (Note 1)
**     ya       double        aim y-coordinate (Note 1)
**     za       double        aim z-coordinate (Note 1)
**
**  Defined in tcs.h:
**     FRAMETYPE   enum       frame types
**     AZEL_TOPO   FRAMETYPE  topocentric Az/El
**
**  Called:  tcsSky2a_c
**
**  Notes:
**
**  1  A "virtual telescope" is a group of transformations that link
**     three sets of coordinates:
**
**       (i)  the target (where in the sky the source is);
**
**      (ii)  the pointing-origin (where in the focal plane the image
**            appears);
**
**     (iii)  the mount encoder readings (that cause the image of the
**            target to fall in the specified place in the focal plane).
**
**     The transformations are specified by various time-dependent
**     rotation matrices, pointing corrections, functions of rotator
**     angle and so on.  They form a chain:
**
**
**                [ TARGET ]             <- target [a,b]
**                     v
**        astronomical transformations   <- time, site
**                     v
**                 refraction            <- weather
**                     v
**              mount orientation        <- ae2mt
**                     v
**                  [ AIM ]
**                     |
**                   roll                <- encoder a, and ia
**                     |
**            roll/pitch nonperp         <- np
**                     |
**                   pitch               <- encoder b, and ib
**                     |
**               [ BORESIGHT ]
**                     |
**                  guiding              <- ga, gb
**                     |
**               pointing origin         <- [x,y] and rotator angle
**                     |
**               [ TELESCOPE ]
**                     |
**                   flop                <- vertical deflection terms
**                     |
**             tel/pitch nonperp         <- collimation terms
**                     |
**                 [ 1,0,0 ]
**
**
**     Given any two of the three sets of coordinates (sky, pointing-
**     origin, mount), the missing coordinates can be deduced.  There is
**     only one mount, and hence all the virtual telescopes must share
**     the same encoder demands, namely those generated by the main
**     "mount tracking" virtual telescope.  The remaining virtual
**     telescopes implement such features as autoguiding and tip/tilt
**     secondary optics, either by deducing the image position for a
**     given target, or deducing the sky coordinates that correspond to
**     a given place in the focal plane.
**
**     In the present case, the AIM vector is calculated, starting
**     from the sky target, as shown by the arrows.
**
**  2  The arguments sst and cst are the sine and cosine of the local
**     apparent sidereal time.  Neither is used if the target frame is
**     topocentric Az/El.
**
**  3  The way frame, spm1, sst, cst and spm2 are used depends on the
**     type of target coordinates:
**
**       frame        FK4
**       target       Bxxxx RA,Dec, current date
**       spm1         mean RA,Dec -> geocentric apparent RA,Dec
**       sst,cst      RA,Dec -> HA,Dec
**       spm2         geocentric HA,Dec -> AIM
**
**       frame        FK5
**       target       Jxxxx RA,Dec, current date
**       spm1         mean RA,Dec -> geocentric apparent RA,Dec
**       sst,cst      RA,Dec -> HA,Dec
**       spm2         geocentric HA,Dec -> AIM
**
**       frame        APPT
**       target       geocentric apparent RA,Dec
**       spm1         identity matrix
**       sst,cst      RA,Dec -> HA,Dec
**       spm2         geocentric HA,Dec -> AIM
**
**       frame        APPT_TOPO
**       target       topocentric apparent RA,Dec
**       spm1         identity matrix
**       sst,cst      RA,Dec -> HA,Dec
**       spm2         topocentric HA,Dec -> AIM
**
**       frame        AZEL_TOPO
**       target       topocentric Az,El (N thru E)
**       spm1         identity matrix
**       sst,cst      not used
**       spm2         topocentric Az,El -> AIM
**
**     ICRS = FK5 J2000 to better than 25 mas.
**
**  4  This routine is optimized for speed, and accordingly no
**     validation of the arguments is performed.  It is the caller's
**     responsibility to supply sensible values.
**
**  Last revision:   19 July 2005
**
**  Copyright P.T.Wallace.  All rights reserved.
*/

{
   double cosb, xtar, ytar, ztar;



/* Current target coordinates, spherical to Cartesian. */
   cosb = cos ( tarb );
   xtar = cos ( tara ) * cosb;
   ytar = sin ( tara ) * cosb;
   ztar = sin ( tarb );
   if ( frame == AZEL_TOPO ) xtar = -xtar;

/* Transformation. */
   tcsSky2a_c ( xtar, ytar, ztar, spm1, frame, sst, cst, spm2,
                xa, ya, za );

}
