#include "tcs.h"

void tcsVTsky_c ( double enca, double encb, ROTLOC rotl, double rma,
                  double xpo, double ypo,
                  double spm1_i[3][3],
                  FRAMETYPE frame, double sst, double cst,
                  double spm2_i[3][3],
                  double ia, double ib, double np,
                  double xt, double yt, double zt,
                  double ga, double gb,
                  double *xs, double *ys, double *zs )

/*
**  - - - - - - - - - - -
**   t c s V T s k y _ c
**  - - - - - - - - - - -
**
**  In a "virtual telescope", calculate the target coordinates that
**  correspond to the specified mount encoder demands and pointing-
**  origin.  The result is in Cartesian coordinates.
**
**  Given:
**     enca     double        mount "roll" encoder demand (Notes 1,2)
**     encb     double        mount "pitch" encoder demand (Notes 1,2)
**     rotl     ROTLOC        rotator location
**     rma      double        rotator mechanical angle
**     xpo      double        pointing-origin x (in focal lengths)
**     ypo      double        pointing-origin y (in focal lengths)
**     spm1_i   double[3][3]  inverse SPM #1 (Note 4)
**     frame    FRAMETYPE     reference frame for the results (Note 4)
**     sst      double        sine of sidereal time (Notes 4,5)
**     cst      double        cosine of sidereal time (Notes 4,5)
**     spm2_i   double[3][3]  inverse SPM #2 (Note 4)
**     ia       double        roll zero point (radians)
**     ib       double        pitch zero point (radians)
**     np       double        mount axes nonperpendicularity (radians)
**     xt       double        telescope vector, x-component (Note 6)
**     yt       double        telescope vector, y-component (Note 6)
**     zt       double        telescope vector, z-component (Note 6)
**     ga       double        guiding correction, collimation
**     gb       double        guiding correction, pitch
**
**  Returned:
**     xs       double*       target x coordinate (Note 2)
**     ys       double*       target y coordinate (Note 2)
**     zs       double*       target z coordinate (Note 2)
**
**  Defined in tcs.h:
**     FRAMETYPE    enum      frame types
**     ROTLOC       enum      rotator locations
**
**  Called:  tcsBs, tcsEnc2aim, tcsAim2s_c
**
**  Notes:
**
**  1  A "virtual telescope" is a group of transformations that link
**     three sets of coordinates:
**
**       (i)  the target (where in the sky the source is);
**
**      (ii)  the pointing-origin (where in the focal plane the image
**            appears);
**
**     (iii)  the mount encoder readings (that cause the image of the
**            target to fall in the specified place in the focal plane).
**
**     The transformations are specified by various time-dependent
**     rotation matrices, pointing corrections, functions of rotator
**     angle and so on.  They form a chain:
**
**
**                [ TARGET ]             -> target [x,y,z]
**                     ^
**        astronomical transformations   <- time, site
**                     ^
**                 refraction            <- weather
**                     ^
**              mount orientation        <- ae2mt
**                     ^
**                  [ AIM ]
**                     ^
**                   roll                <- encoder a, and ia
**                     ^
**            roll/pitch nonperp         <- np
**                     ^
**                   pitch               <- encoder b, and ib
**                     ^
**               [ BORESIGHT ]
**                     ^
**                  guiding              <- ga, gb
**                     ^
**               pointing origin         <- [x,y] and rotator angle
**                     ^
**               [ TELESCOPE ]
**                     ^
**                   flop                <- vertical deflection terms
**                     ^
**             tel/pitch nonperp         <- collimation terms
**                     ^
**                 [ 1,0,0 ]
**
**
**     Given any two of the three sets of coordinates (sky, pointing-
**     origin, mount), the missing coordinates can be deduced.  There is
**     only one mount, and hence all the virtual telescopes must share
**     the same encoder demands, namely those generated by the main
**     "mount tracking" virtual telescope.  The remaining virtual
**     telescopes implement such features as autoguiding and tip/tilt
**     secondary optics, either by deducing the image position for a
**     given target, or deducing the sky coordinates that correspond to
**     a given place in the focal plane.
**
**     In the present case, the encoder values and the pointing-origin
**     coordinates are known, and the target position is to be
**     determined, as shown by the arrows.  The result is in Cartesian
**     coordinates.
**
**  2  If the mount is an altazimuth and the chosen frame is an
**     [RA,Dec], enca is pi-azimuth, encb is elevation, and xs,ys,zs
**     correspond to RA/Dec.  If the mount is an equatorial, enca
**     is -HA and encb is declination.  If the chosen frame is
**     topocentric [Az,El], xs,ys,zs correspond to Az/El.
**
**  3  The arguments sst and cst are the sine and cosine of the local
**     apparent sidereal time.  Neither is used if the target frame is
**     topocentric Az/El.
**
**  4  The way frame, spm1_i, sst, cst and spm2_i are used depends on
**     the type of target coordinates:
**
**       frame        FK4
**       target       Bxxxx RA,Dec, current date
**       spm1_i       mean RA,Dec <- geocentric apparent RA,Dec
**       sst,cst      RA,Dec <- HA,Dec
**       spm2_i       geocentric HA,Dec <- AIM
**
**       frame        FK5
**       target       Jxxxx RA,Dec, current date
**       spm1_i       mean RA,Dec <- geocentric apparent RA,Dec
**       sst,cst      RA,Dec <- HA,Dec
**       spm2_i       geocentric HA,Dec <- AIM
**
**       frame        APPT
**       target       geocentric apparent RA,Dec
**       spm1_i       identity matrix
**       sst,cst      RA,Dec <- HA,Dec
**       spm2_i       geocentric HA,Dec <- AIM
**
**       frame        APPT_TOPO
**       target       topocentric apparent RA,Dec
**       spm1_i       identity matrix
**       sst,cst      RA,Dec <- HA,Dec
**       spm2_i       topocentric HA,Dec <- AIM
**
**       frame        AZEL_TOPO
**       target       topocentric Az,El (N thru E)
**       spm1_i       identity matrix
**       sst,cst      not used
**       spm2_i       topocentric Az,El <- AIM
**
**     ICRS = FK5 J2000 to better than 25 mas.
**
**  5  The TELESCOPE vector [xt,yt,zt] is in this frame:
**
**       x-axis:  at right angles to both the roll and pitch axes
**       y-axis:  along the pitch axis
**       z-axis:  at right angles to the other two axes
**
**     In the absence of either collimation error or vertical deflection
**     the TELESCOPE vector is [1,0,0].
**
**  6  This routine is optimized for speed, and accordingly no validation
**     of the arguments is performed.  It is the caller's responsibility
**     to supply sensible values.
**
**  Last revision:   3 March 2005
**
**  Copyright P.T.Wallace.  All rights reserved.
*/

{
   double xb, yb, zb, xa, ya, za;



/* Obtain the BORESIGHT vector. */
   tcsBs ( xt, yt, zt, rotl, rma, enca, encb, ga, gb, xpo, ypo,
           &xb, &yb, &zb );

/* Rotate by mount posture to give AIM vector. */
   tcsEnc2aim ( enca, encb, xb, yb, zb, ia, ib, np, &xa, &ya, &za );

/* To sky. */
   tcsAim2s_c ( xa, ya, za, spm1_i, frame, sst, cst, spm2_i, xs, ys, zs );

}
