#include "tcs.h"

void tcsVTxe_c ( double xtar, double ytar, double ztar,
                 double spm1[3][3],
                 FRAMETYPE frame, double sst, double cst,
                 double spm2[3][3],
                 double enca, double encb,
                 double ia, double ib, double np,
                 double xt, double yt, double zt,
                 double ga, double gb,
                 double *xiim, double *etaim, int *j )

/*
**  - - - - - - - - - -
**   t c s V T x e _ c
**  - - - - - - - - - -
**
**  In a "virtual telescope", given the position of a target (e.g. a
**  guide-star), and knowing the telescope encoder settings, determine
**  the (xi,eta) coordinates of the image in the non-rotating focal
**  plane.  The target is specified in Cartesian form.
**
**  Given:
**     xtar     double        target x-coordinate (Notes 1,2)
**     ytar     double        target y-coordinate (Notes 1,2)
**     ztar     double        target z-coordinate (Notes 1,2)
**     spm1     double[3][3]  SPM #1 (Note 4)
**     frame    FRAMETYPE     reference frame for the target (Note 4)
**     sst      double        sine of sidereal time (Notes 3,4)
**     cst      double        cosine of sidereal time (Notes 3,4)
**     spm2     double[3][3]  SPM #2 (Note 4)
**     enca     double        encoder roll coordinate
**     encb     double        encoder pitch coordinate
**     ia       double        roll zero point (radians)
**     ib       double        pitch zero point (radians)
**     np       double        mount axes nonperpendicularity (radians)
**     xt       double        telescope vector, x-component (Note 5)
**     yt       double        telescope vector, y-component (Note 5)
**     zt       double        telescope vector, z-component (Note 5)
**     ga       double        guiding correction, collimation
**     gb       double        guiding correction, pitch
**
**  Returned:
**     xiim     double        image x-coordinate (Note 6)
**     etaim    double        image y-coordinate (Note 6)
**     j        int           status:    0 = OK
**                                    else = star cannot be imaged
**
**  Defined in tcs.h:
**     FRAMETYPE   enum       frame types
**
**  Called:  tcsSky2a_c, tcsAim2xe
**
**  Notes:
**
**  1  A "virtual telescope" is a group of transformations that link
**     three sets of coordinates:
**
**       (i)  the target (where in the sky the source is);
**
**      (ii)  the pointing-origin (where in the focal plane the image
**            appears);
**
**     (iii)  the mount encoder readings (that cause the image of the
**            target to fall in the specified place in the focal plane).
**
**     The transformations are specified by various time-dependent
**     rotation matrices, pointing corrections, functions of rotator
**     angle and so on.  They form a chain:
**
**
**                [ TARGET ]             <- target [a,b]
**                     v
**        astronomical transformations   <- time, site
**                     v
**                 refraction            <- weather
**                     v
**              mount orientation        <- ae2mt
**                     v
**                  [ AIM ]
**                     v
**                   roll                <- encoder a, and ia
**                     v
**            roll/pitch nonperp         <- np
**                     v
**                   pitch               <- encoder b, and ib
**                     v
**               [ BORESIGHT ]
**                     v
**                  guiding              <- ga, gb
**                     v
**               pointing origin         -> [xi,eta]
**                     ^
**               [ TELESCOPE ]
**                     ^
**                   flop                <- vertical deflection terms
**                     ^
**             tel/pitch nonperp         <- collimation terms
**                     ^
**                 [ 1,0,0 ]
**
**
**     Given any two of the three sets of coordinates (sky, pointing-
**     origin, mount), the missing coordinates can be deduced.  There is
**     only one mount, and hence all the virtual telescopes must share
**     the same encoder demands, namely those generated by the main
**     "mount tracking" virtual telescope.  The remaining virtual
**     telescopes implement such features as autoguiding and tip/tilt
**     secondary optics, either by deducing the image position for a
**     given target, or deducing the sky coordinates that correspond to
**     a given place in the focal plane.
**
**     In the present case, the pointing origin is determined, starting
**     from the sky target coordinates and the encoder settings, as
**     shown by the arrows.
**
**  2  The target vector is right-handed, so special care must be taken
**     if using Az/El, which is a left-handed system.  The procedure in
**     this case is to perform the standard spherical-to-Cartesian
**     transformation and then to reverse the sign of the x-coordinate.
**
**  3  The arguments sst and cst are the sine and cosine of the local
**     apparent sidereal time.  Neither is used if the target frame is
**     topocentric Az/El.
**
**  4  The way frame, spm1, sst, cst and spm2 are used depends on the
**     type of target coordinates:
**
**       frame        FK4
**       target       Bxxxx RA,Dec, current date
**       spm1         mean RA,Dec -> geocentric apparent RA,Dec
**       sst,cst      RA,Dec -> HA,Dec
**       spm2         geocentric HA,Dec -> AIM
**
**       frame        FK5
**       target       Jxxxx RA,Dec, current date
**       spm1         mean RA,Dec -> geocentric apparent RA,Dec
**       sst,cst      RA,Dec -> HA,Dec
**       spm2         geocentric HA,Dec -> AIM
**
**       frame        APPT
**       target       geocentric apparent RA,Dec
**       spm1         identity matrix
**       sst,cst      RA,Dec -> HA,Dec
**       spm2         geocentric HA,Dec -> AIM
**
**       frame        APPT_TOPO
**       target       topocentric apparent RA,Dec
**       spm1         identity matrix
**       sst,cst      RA,Dec -> HA,Dec
**       spm2         topocentric HA,Dec -> AIM
**
**       frame        AZEL_TOPO
**       target       topocentric Az,El (N thru E)
**       spm1         identity matrix
**       sst,cst      not used
**       spm2         topocentric Az,El -> AIM
**
**     ICRS = FK5 J2000 to better than 25 mas.
**
**  5  The TELESCOPE vector [xt,yt,zt] is in this frame:
**
**       x-axis:  at right angles to both the roll and pitch axes
**       y-axis:  along the pitch axis
**       z-axis:  at right angles to the other two axes
**
**     In the absence of either collimation error or vertical deflection
**     the TELESCOPE vector is [1,0,0].
**
**  6  The image coordinates returned, xiim and etaim, are in the
**     non-rotating focal plane and are in units of one focal length.
**     The companion function tcsVTxy is similar but returns x,y
**     coordinates in the rotating focal plane.
**
**  7  A common application for this routine is controlling a tip/tilt
**     subreflector.
**
**  8  This routine is optimized for speed, and accordingly only minimal
**     validation of the arguments is performed.  It is the caller's
**     responsibility to supply sensible and safe values.
**
**  Last revision:   19 July 2005
**
**  Copyright P.T.Wallace.  All rights reserved.
*/

{
   double xa, ya, za, a, b, xi, eta;



/* SKY target vector to AIM roll/pitch vector. */
   tcsSky2a_c ( xtar, ytar, ztar, spm1, frame, sst, cst, spm2,
                &xa, &ya, &za );

/* Incorporate the index errors into the roll/pitch. */
   a = enca + ia;
   b = encb + ib;

/* Determine the image [xi,eta]. */
   tcsAim2xe ( xa, ya, za, a, b, np, xt, yt, zt, &xi, &eta, j );

/* Omit the guiding contributions from the result. */
   *xiim = xi - ga;
   *etaim = eta - gb;

}
